sudo: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install: 
- pip install tox-travis
- pip install -r dev-requirements.txt
- pip install flake8 pep8-naming
script:
- tox
- flake8 . 
